### ISSUE TITLE
Install a chrome-based Browser

### ISSUE THREAD

**Issue by codingbootcampseu** [ChristianMLux/bootcamp-schedule#3]
Most developers out there use a Chrome-based browser to develop web applications. While Edge, Safari and all other browsers work well we will use a Chrome-based browser in this bootcamp.

You can either install [Google Chrome](https://www.google.com/chrome/) or (if you prefer privacy) you can install the [Brave Browser](https://brave.com/) (which is indeed a Chrome without any sniffing parts).

> Recommendation: Use the [Brave Browser](https://brave.com/) 🔥

**Comment by ChristianMLux** [comment]
already done.
